/*
  Copyright 2018 - 2023 denk & dachte Software GmbH

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.13 at 10:15:10 AM CEST 
//


package de.denkunddachte.sspcmapi.cd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="createdTimestamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="encryptionLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="engines" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="engine" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="engineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="psInName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="psOutName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="eaPSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="eaServerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="icapPSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="icapServerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="startupMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="useEA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="faspPortrange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="forceToUnlock" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="formatVer" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="formatVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="icapScanOption" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastModifiedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastModifiedTimestamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listenPort" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="lockedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lockedTimestamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="logLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxSessions" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="netmap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="netmapKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pingResponse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="properties" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="property" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="protocol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="psOutPortrange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sessionTimeout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="standardRoute" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="urlRoutingType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="verStamp" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createdBy",
    "createdTimestamp",
    "description",
    "encryptionLevel",
    "engines",
    "faspPortrange",
    "forceToUnlock",
    "formatVer",
    "formatVersion",
    "icapScanOption",
    "lastModifiedBy",
    "lastModifiedTimestamp",
    "listenPort",
    "lockedBy",
    "lockedTimestamp",
    "logLevel",
    "maxSessions",
    "name",
    "netmap",
    "netmapKey",
    "pingResponse",
    "properties",
    "protocol",
    "psOutPortrange",
    "sessionTimeout",
    "standardRoute",
    "status",
    "urlRoutingType",
    "verStamp"
})
@XmlRootElement(name = "cdAdapterDef")
public class CdAdapterDef {

    protected String createdBy;
    protected String createdTimestamp;
    protected String description;
    protected String encryptionLevel;
    protected CdAdapterDef.Engines engines;
    protected String faspPortrange;
    protected String forceToUnlock;
    protected Integer formatVer;
    protected Integer formatVersion;
    protected String icapScanOption;
    protected String lastModifiedBy;
    protected String lastModifiedTimestamp;
    protected Integer listenPort;
    protected String lockedBy;
    protected String lockedTimestamp;
    protected String logLevel;
    protected Integer maxSessions;
    protected String name;
    protected String netmap;
    protected String netmapKey;
    protected String pingResponse;
    protected CdAdapterDef.Properties properties;
    protected String protocol;
    protected String psOutPortrange;
    protected Integer sessionTimeout;
    protected String standardRoute;
    protected String status;
    protected String urlRoutingType;
    protected Integer verStamp;

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedBy(String value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the createdTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedTimestamp() {
        return createdTimestamp;
    }

    /**
     * Sets the value of the createdTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedTimestamp(String value) {
        this.createdTimestamp = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the encryptionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptionLevel() {
        return encryptionLevel;
    }

    /**
     * Sets the value of the encryptionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptionLevel(String value) {
        this.encryptionLevel = value;
    }

    /**
     * Gets the value of the engines property.
     * 
     * @return
     *     possible object is
     *     {@link CdAdapterDef.Engines }
     *     
     */
    public CdAdapterDef.Engines getEngines() {
        return engines;
    }

    /**
     * Sets the value of the engines property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdAdapterDef.Engines }
     *     
     */
    public void setEngines(CdAdapterDef.Engines value) {
        this.engines = value;
    }

    /**
     * Gets the value of the faspPortrange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaspPortrange() {
        return faspPortrange;
    }

    /**
     * Sets the value of the faspPortrange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaspPortrange(String value) {
        this.faspPortrange = value;
    }

    /**
     * Gets the value of the forceToUnlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForceToUnlock() {
        return forceToUnlock;
    }

    /**
     * Sets the value of the forceToUnlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForceToUnlock(String value) {
        this.forceToUnlock = value;
    }

    /**
     * Gets the value of the formatVer property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFormatVer() {
        return formatVer;
    }

    /**
     * Sets the value of the formatVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFormatVer(Integer value) {
        this.formatVer = value;
    }

    /**
     * Gets the value of the formatVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFormatVersion() {
        return formatVersion;
    }

    /**
     * Sets the value of the formatVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFormatVersion(Integer value) {
        this.formatVersion = value;
    }

    /**
     * Gets the value of the icapScanOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcapScanOption() {
        return icapScanOption;
    }

    /**
     * Sets the value of the icapScanOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcapScanOption(String value) {
        this.icapScanOption = value;
    }

    /**
     * Gets the value of the lastModifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * Sets the value of the lastModifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastModifiedBy(String value) {
        this.lastModifiedBy = value;
    }

    /**
     * Gets the value of the lastModifiedTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastModifiedTimestamp() {
        return lastModifiedTimestamp;
    }

    /**
     * Sets the value of the lastModifiedTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastModifiedTimestamp(String value) {
        this.lastModifiedTimestamp = value;
    }

    /**
     * Gets the value of the listenPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getListenPort() {
        return listenPort;
    }

    /**
     * Sets the value of the listenPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setListenPort(Integer value) {
        this.listenPort = value;
    }

    /**
     * Gets the value of the lockedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLockedBy() {
        return lockedBy;
    }

    /**
     * Sets the value of the lockedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLockedBy(String value) {
        this.lockedBy = value;
    }

    /**
     * Gets the value of the lockedTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLockedTimestamp() {
        return lockedTimestamp;
    }

    /**
     * Sets the value of the lockedTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLockedTimestamp(String value) {
        this.lockedTimestamp = value;
    }

    /**
     * Gets the value of the logLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogLevel() {
        return logLevel;
    }

    /**
     * Sets the value of the logLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogLevel(String value) {
        this.logLevel = value;
    }

    /**
     * Gets the value of the maxSessions property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxSessions() {
        return maxSessions;
    }

    /**
     * Sets the value of the maxSessions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxSessions(Integer value) {
        this.maxSessions = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the netmap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetmap() {
        return netmap;
    }

    /**
     * Sets the value of the netmap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetmap(String value) {
        this.netmap = value;
    }

    /**
     * Gets the value of the netmapKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetmapKey() {
        return netmapKey;
    }

    /**
     * Sets the value of the netmapKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetmapKey(String value) {
        this.netmapKey = value;
    }

    /**
     * Gets the value of the pingResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPingResponse() {
        return pingResponse;
    }

    /**
     * Sets the value of the pingResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPingResponse(String value) {
        this.pingResponse = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link CdAdapterDef.Properties }
     *     
     */
    public CdAdapterDef.Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdAdapterDef.Properties }
     *     
     */
    public void setProperties(CdAdapterDef.Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol(String value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the psOutPortrange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsOutPortrange() {
        return psOutPortrange;
    }

    /**
     * Sets the value of the psOutPortrange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsOutPortrange(String value) {
        this.psOutPortrange = value;
    }

    /**
     * Gets the value of the sessionTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSessionTimeout() {
        return sessionTimeout;
    }

    /**
     * Sets the value of the sessionTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSessionTimeout(Integer value) {
        this.sessionTimeout = value;
    }

    /**
     * Gets the value of the standardRoute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardRoute() {
        return standardRoute;
    }

    /**
     * Sets the value of the standardRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardRoute(String value) {
        this.standardRoute = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the urlRoutingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlRoutingType() {
        return urlRoutingType;
    }

    /**
     * Sets the value of the urlRoutingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlRoutingType(String value) {
        this.urlRoutingType = value;
    }

    /**
     * Gets the value of the verStamp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVerStamp() {
        return verStamp;
    }

    /**
     * Sets the value of the verStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVerStamp(Integer value) {
        this.verStamp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="engine" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="engineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="psInName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="psOutName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="eaPSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="eaServerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="icapPSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="icapServerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="startupMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="useEA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "engine"
    })
    public static class Engines {

        @XmlElement(nillable = true)
        protected List<CdAdapterDef.Engines.Engine> engine;

        /**
         * Gets the value of the engine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the engine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEngine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CdAdapterDef.Engines.Engine }
         * 
         * 
         */
        public List<CdAdapterDef.Engines.Engine> getEngine() {
            if (engine == null) {
                engine = new ArrayList<CdAdapterDef.Engines.Engine>();
            }
            return this.engine;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="engineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="psInName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="psOutName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="eaPSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="eaServerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="icapPSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="icapServerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="startupMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="useEA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "engineName",
            "psInName",
            "psOutName",
            "eaPSName",
            "eaServerName",
            "icapPSName",
            "icapServerName",
            "startupMode",
            "useEA"
        })
        public static class Engine {

            protected String engineName;
            protected String psInName;
            protected String psOutName;
            protected String eaPSName;
            protected String eaServerName;
            protected String icapPSName;
            protected String icapServerName;
            protected String startupMode;
            protected String useEA;

            /**
             * Gets the value of the engineName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEngineName() {
                return engineName;
            }

            /**
             * Sets the value of the engineName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEngineName(String value) {
                this.engineName = value;
            }

            /**
             * Gets the value of the psInName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPsInName() {
                return psInName;
            }

            /**
             * Sets the value of the psInName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPsInName(String value) {
                this.psInName = value;
            }

            /**
             * Gets the value of the psOutName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPsOutName() {
                return psOutName;
            }

            /**
             * Sets the value of the psOutName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPsOutName(String value) {
                this.psOutName = value;
            }

            /**
             * Gets the value of the eaPSName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEaPSName() {
                return eaPSName;
            }

            /**
             * Sets the value of the eaPSName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEaPSName(String value) {
                this.eaPSName = value;
            }

            /**
             * Gets the value of the eaServerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEaServerName() {
                return eaServerName;
            }

            /**
             * Sets the value of the eaServerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEaServerName(String value) {
                this.eaServerName = value;
            }

            /**
             * Gets the value of the icapPSName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIcapPSName() {
                return icapPSName;
            }

            /**
             * Sets the value of the icapPSName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIcapPSName(String value) {
                this.icapPSName = value;
            }

            /**
             * Gets the value of the icapServerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIcapServerName() {
                return icapServerName;
            }

            /**
             * Sets the value of the icapServerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIcapServerName(String value) {
                this.icapServerName = value;
            }

            /**
             * Gets the value of the startupMode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartupMode() {
                return startupMode;
            }

            /**
             * Sets the value of the startupMode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartupMode(String value) {
                this.startupMode = value;
            }

            /**
             * Gets the value of the useEA property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUseEA() {
                return useEA;
            }

            /**
             * Sets the value of the useEA property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUseEA(String value) {
                this.useEA = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="property" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "property"
    })
    public static class Properties {

        @XmlElement(nillable = true)
        protected List<CdAdapterDef.Properties.Property> property;

        /**
         * Gets the value of the property property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CdAdapterDef.Properties.Property }
         * 
         * 
         */
        public List<CdAdapterDef.Properties.Property> getProperty() {
            if (property == null) {
                property = new ArrayList<CdAdapterDef.Properties.Property>();
            }
            return this.property;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "value"
        })
        public static class Property {

            protected String name;
            protected String value;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }

}
