/*
  Copyright 2018 - 2023 denk & dachte Software GmbH

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.13 at 10:15:10 AM CEST 
//

package de.denkunddachte.sspcmapi.cd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inboundNodeDef" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="addresses" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="address" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="nodeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="destinationServiceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="forceToUnlock" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="formatVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="logLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="outboundACLNodes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="outboundACLNode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="peerAddressPattern" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="policyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="routingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="routingNode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="secureConnection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="serverAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="socksProxyServerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="socksProxyServerPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="socksProxyServerUserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="sslInfo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="certificateCommonName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="cipherSuites" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="cipherSuite" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="clientAuthenticationCD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="keyCertName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="keyStoreName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="protocol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="trustStoreName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="trustedCertNames" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="trustedCertName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="verifyCommonName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="stepInjection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="tcpTimeout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="verStamp" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "inboundNodeDef" })
@XmlRootElement(name = "inboundNodes")
public class InboundNodes {

  @XmlElement(nillable = true)
  protected List<InboundNodes.InboundNodeDef> inboundNodeDef;

  /**
   * Gets the value of the inboundNodeDef property.
   * 
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the inboundNodeDef property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getInboundNodeDef().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link InboundNodes.InboundNodeDef }
   * 
   * 
   */
  public List<InboundNodes.InboundNodeDef> getInboundNodeDef() {
    if (inboundNodeDef == null) {
      inboundNodeDef = new ArrayList<InboundNodes.InboundNodeDef>();
    }
    return this.inboundNodeDef;
  }

  /**
   * <p>Java class for anonymous complex type.
   * 
   * <p>The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="addresses" minOccurs="0">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="address" maxOccurs="unbounded" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="nodeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                             &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                             &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
   *                           &lt;/sequence>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="destinationServiceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="forceToUnlock" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="formatVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
   *         &lt;element name="logLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="outboundACLNodes" minOccurs="0">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="outboundACLNode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="peerAddressPattern" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="policyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
   *         &lt;element name="routingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="routingNode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="secureConnection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="serverAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="socksProxyServerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="socksProxyServerPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="socksProxyServerUserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="sslInfo" minOccurs="0">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="certificateCommonName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                   &lt;element name="cipherSuites" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="cipherSuite" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
   *                           &lt;/sequence>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                   &lt;element name="clientAuthenticationCD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                   &lt;element name="keyCertName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                   &lt;element name="keyStoreName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                   &lt;element name="protocol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                   &lt;element name="trustStoreName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                   &lt;element name="trustedCertNames" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="trustedCertName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
   *                           &lt;/sequence>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                   &lt;element name="verifyCommonName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="stepInjection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *         &lt;element name="tcpTimeout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
   *         &lt;element name="verStamp" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "",
      propOrder = { "addresses", "description", "destinationServiceName", "forceToUnlock", "formatVersion", "logLevel", "name", "outboundACLNodes",
          "peerAddressPattern", "policyId", "port", "routingName", "routingNode", "secureConnection", "serverAddress", "socksProxyServerName",
          "socksProxyServerPassword", "socksProxyServerUserId", "sslInfo", "stepInjection", "tcpTimeout", "verStamp" })
  public static class InboundNodeDef {

    protected InboundNodes.InboundNodeDef.Addresses        addresses;
    protected String                                       description;
    protected String                                       destinationServiceName;
    protected boolean                                      forceToUnlock;
    protected Integer                                      formatVersion;
    protected String                                       logLevel;
    protected String                                       name;
    protected InboundNodes.InboundNodeDef.OutboundACLNodes outboundACLNodes;
    protected String                                       peerAddressPattern;
    protected String                                       policyId;
    protected Integer                                      port;
    protected String                                       routingName;
    protected String                                       routingNode;
    protected boolean                                      secureConnection;
    protected String                                       serverAddress;
    protected String                                       socksProxyServerName;
    protected String                                       socksProxyServerPassword;
    protected String                                       socksProxyServerUserId;
    protected InboundNodes.InboundNodeDef.SslInfo          sslInfo;
    protected String                                       stepInjection;
    protected Integer                                      tcpTimeout;
    protected Integer                                      verStamp;

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link InboundNodes.InboundNodeDef.Addresses }
     *     
     */
    public InboundNodes.InboundNodeDef.Addresses getAddresses() {
      if (addresses == null) {
        addresses = new InboundNodes.InboundNodeDef.Addresses();
      }
      return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundNodes.InboundNodeDef.Addresses }
     *     
     */
    public void setAddresses(InboundNodes.InboundNodeDef.Addresses value) {
      this.addresses = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
      return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
      this.description = value;
    }

    /**
     * Gets the value of the destinationServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationServiceName() {
      return destinationServiceName;
    }

    /**
     * Sets the value of the destinationServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationServiceName(String value) {
      this.destinationServiceName = value;
    }

    /**
     * Gets the value of the forceToUnlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public boolean getForceToUnlock() {
      return forceToUnlock;
    }

    /**
     * Sets the value of the forceToUnlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForceToUnlock(boolean value) {
      this.forceToUnlock = value;
    }

    /**
     * Gets the value of the formatVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFormatVersion() {
      return formatVersion;
    }

    /**
     * Sets the value of the formatVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFormatVersion(Integer value) {
      this.formatVersion = value;
    }

    /**
     * Gets the value of the logLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogLevel() {
      return logLevel;
    }

    /**
     * Sets the value of the logLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogLevel(String value) {
      this.logLevel = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
      return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
      this.name = value;
    }

    /**
     * Gets the value of the outboundACLNodes property.
     * 
     * @return
     *     possible object is
     *     {@link InboundNodes.InboundNodeDef.OutboundACLNodes }
     *     
     */
    public InboundNodes.InboundNodeDef.OutboundACLNodes getOutboundACLNodes() {
      if (outboundACLNodes == null) {
        outboundACLNodes = new InboundNodes.InboundNodeDef.OutboundACLNodes();
      }
      return outboundACLNodes;
    }

    /**
     * Sets the value of the outboundACLNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundNodes.InboundNodeDef.OutboundACLNodes }
     *     
     */
    public void setOutboundACLNodes(InboundNodes.InboundNodeDef.OutboundACLNodes value) {
      this.outboundACLNodes = value;
    }

    /**
     * Gets the value of the peerAddressPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeerAddressPattern() {
      return peerAddressPattern;
    }

    /**
     * Sets the value of the peerAddressPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeerAddressPattern(String value) {
      this.peerAddressPattern = value;
    }

    /**
     * Gets the value of the policyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyId() {
      return policyId;
    }

    /**
     * Sets the value of the policyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyId(String value) {
      this.policyId = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPort() {
      return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPort(Integer value) {
      this.port = value;
    }

    /**
     * Gets the value of the routingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutingName() {
      return routingName;
    }

    /**
     * Sets the value of the routingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutingName(String value) {
      this.routingName = value;
    }

    /**
     * Gets the value of the routingNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutingNode() {
      return routingNode;
    }

    /**
     * Sets the value of the routingNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutingNode(String value) {
      this.routingNode = value;
    }

    /**
     * Gets the value of the secureConnection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public boolean getSecureConnection() {
      return secureConnection;
    }

    /**
     * Sets the value of the secureConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecureConnection(boolean value) {
      this.secureConnection = value;
    }

    /**
     * Gets the value of the serverAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerAddress() {
      return serverAddress;
    }

    /**
     * Sets the value of the serverAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerAddress(String value) {
      this.serverAddress = value;
    }

    /**
     * Gets the value of the socksProxyServerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocksProxyServerName() {
      return socksProxyServerName;
    }

    /**
     * Sets the value of the socksProxyServerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocksProxyServerName(String value) {
      this.socksProxyServerName = value;
    }

    /**
     * Gets the value of the socksProxyServerPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocksProxyServerPassword() {
      return socksProxyServerPassword;
    }

    /**
     * Sets the value of the socksProxyServerPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocksProxyServerPassword(String value) {
      this.socksProxyServerPassword = value;
    }

    /**
     * Gets the value of the socksProxyServerUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocksProxyServerUserId() {
      return socksProxyServerUserId;
    }

    /**
     * Sets the value of the socksProxyServerUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocksProxyServerUserId(String value) {
      this.socksProxyServerUserId = value;
    }

    /**
     * Gets the value of the sslInfo property.
     * 
     * @return
     *     possible object is
     *     {@link InboundNodes.InboundNodeDef.SslInfo }
     *     
     */
    public InboundNodes.InboundNodeDef.SslInfo getSslInfo() {
      return sslInfo;
    }

    /**
     * Sets the value of the sslInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundNodes.InboundNodeDef.SslInfo }
     *     
     */
    public void setSslInfo(InboundNodes.InboundNodeDef.SslInfo value) {
      this.sslInfo = value;
    }

    /**
     * Gets the value of the stepInjection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStepInjection() {
      return stepInjection;
    }

    /**
     * Sets the value of the stepInjection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStepInjection(String value) {
      this.stepInjection = value;
    }

    /**
     * Gets the value of the tcpTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTcpTimeout() {
      return tcpTimeout;
    }

    /**
     * Sets the value of the tcpTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTcpTimeout(Integer value) {
      this.tcpTimeout = value;
    }

    /**
     * Gets the value of the verStamp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVerStamp() {
      return verStamp;
    }

    /**
     * Sets the value of the verStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVerStamp(Integer value) {
      this.verStamp = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="address" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nodeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "address" })
    public static class Addresses {

      @XmlElement(nillable = true)
      protected List<InboundNodes.InboundNodeDef.Addresses.Address> address;

      /**
       * Gets the value of the address property.
       * 
       * <p>
       * This accessor method returns a reference to the live list,
       * not a snapshot. Therefore any modification you make to the
       * returned list will be present inside the JAXB object.
       * This is why there is not a <CODE>set</CODE> method for the address property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * <pre>
       *    getAddress().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list
       * {@link InboundNodes.InboundNodeDef.Addresses.Address }
       * 
       * 
       */
      public List<InboundNodes.InboundNodeDef.Addresses.Address> getAddress() {
        if (address == null) {
          address = new ArrayList<>();
        }
        return this.address;
      }

      /**
       * <p>Java class for anonymous complex type.
       * 
       * <p>The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="nodeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
       *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
       *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
       *       &lt;/sequence>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "nodeName", "host", "port" })
      public static class Address {

        protected String  nodeName;
        protected String  host;
        protected Integer port;

        /**
         * Gets the value of the nodeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNodeName() {
          return nodeName;
        }

        /**
         * Sets the value of the nodeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNodeName(String value) {
          this.nodeName = value;
        }

        /**
         * Gets the value of the host property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHost() {
          return host;
        }

        /**
         * Sets the value of the host property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHost(String value) {
          this.host = value;
        }

        /**
         * Gets the value of the port property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPort() {
          return port;
        }

        /**
         * Sets the value of the port property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPort(Integer value) {
          this.port = value;
        }

      }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="outboundACLNode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "outboundACLNode" })
    public static class OutboundACLNodes {

      @XmlElement(nillable = true)
      protected List<String> outboundACLNode;

      /**
       * Gets the value of the outboundACLNode property.
       * 
       * <p>
       * This accessor method returns a reference to the live list,
       * not a snapshot. Therefore any modification you make to the
       * returned list will be present inside the JAXB object.
       * This is why there is not a <CODE>set</CODE> method for the outboundACLNode property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * <pre>
       *    getOutboundACLNode().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list
       * {@link String }
       * 
       * 
       */
      public List<String> getOutboundACLNode() {
        if (outboundACLNode == null) {
          outboundACLNode = new ArrayList<String>();
        }
        return this.outboundACLNode;
      }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="certificateCommonName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cipherSuites" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cipherSuite" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="clientAuthenticationCD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="keyCertName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="keyStoreName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="protocol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="trustStoreName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="trustedCertNames" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="trustedCertName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="verifyCommonName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "certificateCommonName", "cipherSuites", "clientAuthenticationCD", "keyCertName", "keyStoreName", "protocol",
        "trustStoreName", "trustedCertNames", "verifyCommonName" })
    public static class SslInfo {

      protected String                                               certificateCommonName;
      protected InboundNodes.InboundNodeDef.SslInfo.CipherSuites     cipherSuites;
      protected boolean                                              clientAuthenticationCD;
      protected String                                               keyCertName;
      protected String                                               keyStoreName;
      protected String                                               protocol;
      protected String                                               trustStoreName;
      protected InboundNodes.InboundNodeDef.SslInfo.TrustedCertNames trustedCertNames;
      protected boolean                                              verifyCommonName;

      /**
       * Gets the value of the certificateCommonName property.
       * 
       * @return
       *     possible object is
       *     {@link String }
       *     
       */
      public String getCertificateCommonName() {
        return certificateCommonName;
      }

      /**
       * Sets the value of the certificateCommonName property.
       * 
       * @param value
       *     allowed object is
       *     {@link String }
       *     
       */
      public void setCertificateCommonName(String value) {
        this.certificateCommonName = value;
      }

      /**
       * Gets the value of the cipherSuites property.
       * 
       * @return
       *     possible object is
       *     {@link InboundNodes.InboundNodeDef.SslInfo.CipherSuites }
       *     
       */
      public InboundNodes.InboundNodeDef.SslInfo.CipherSuites getCipherSuites() {
        if (this.cipherSuites == null) {
          this.cipherSuites = new InboundNodes.InboundNodeDef.SslInfo.CipherSuites();
        }
        return cipherSuites;
      }

      /**
       * Sets the value of the cipherSuites property.
       * 
       * @param value
       *     allowed object is
       *     {@link InboundNodes.InboundNodeDef.SslInfo.CipherSuites }
       *     
       */
      public void setCipherSuites(InboundNodes.InboundNodeDef.SslInfo.CipherSuites value) {
        this.cipherSuites = value;
      }

      /**
       * Gets the value of the clientAuthenticationCD property.
       * 
       * @return
       *     possible object is
       *     {@link String }
       *     
       */
      public boolean getClientAuthenticationCD() {
        return clientAuthenticationCD;
      }

      /**
       * Sets the value of the clientAuthenticationCD property.
       * 
       * @param value
       *     allowed object is
       *     {@link String }
       *     
       */
      public void setClientAuthenticationCD(boolean value) {
        this.clientAuthenticationCD = value;
      }

      /**
       * Gets the value of the keyCertName property.
       * 
       * @return
       *     possible object is
       *     {@link String }
       *     
       */
      public String getKeyCertName() {
        return keyCertName;
      }

      /**
       * Sets the value of the keyCertName property.
       * 
       * @param value
       *     allowed object is
       *     {@link String }
       *     
       */
      public void setKeyCertName(String value) {
        this.keyCertName = value;
      }

      /**
       * Gets the value of the keyStoreName property.
       * 
       * @return
       *     possible object is
       *     {@link String }
       *     
       */
      public String getKeyStoreName() {
        return keyStoreName;
      }

      /**
       * Sets the value of the keyStoreName property.
       * 
       * @param value
       *     allowed object is
       *     {@link String }
       *     
       */
      public void setKeyStoreName(String value) {
        this.keyStoreName = value;
      }

      /**
       * Gets the value of the protocol property.
       * 
       * @return
       *     possible object is
       *     {@link String }
       *     
       */
      public String getProtocol() {
        return protocol;
      }

      /**
       * Sets the value of the protocol property.
       * 
       * @param value
       *     allowed object is
       *     {@link String }
       *     
       */
      public void setProtocol(String value) {
        this.protocol = value;
      }

      /**
       * Gets the value of the trustStoreName property.
       * 
       * @return
       *     possible object is
       *     {@link String }
       *     
       */
      public String getTrustStoreName() {
        return trustStoreName;
      }

      /**
       * Sets the value of the trustStoreName property.
       * 
       * @param value
       *     allowed object is
       *     {@link String }
       *     
       */
      public void setTrustStoreName(String value) {
        this.trustStoreName = value;
      }

      /**
       * Gets the value of the trustedCertNames property.
       * 
       * @return
       *     possible object is
       *     {@link InboundNodes.InboundNodeDef.SslInfo.TrustedCertNames }
       *     
       */
      public InboundNodes.InboundNodeDef.SslInfo.TrustedCertNames getTrustedCertNames() {
        if (this.trustedCertNames == null) {
          this.trustedCertNames = new InboundNodes.InboundNodeDef.SslInfo.TrustedCertNames();
        }
        return this.trustedCertNames;
      }

      /**
       * Sets the value of the trustedCertNames property.
       * 
       * @param value
       *     allowed object is
       *     {@link InboundNodes.InboundNodeDef.SslInfo.TrustedCertNames }
       *     
       */
      public void setTrustedCertNames(InboundNodes.InboundNodeDef.SslInfo.TrustedCertNames value) {
        this.trustedCertNames = value;
      }

      /**
       * Gets the value of the verifyCommonName property.
       * 
       * @return
       *     possible object is
       *     {@link String }
       *     
       */
      public boolean getVerifyCommonName() {
        return verifyCommonName;
      }

      /**
       * Sets the value of the verifyCommonName property.
       * 
       * @param value
       *     allowed object is
       *     {@link String }
       *     
       */
      public void setVerifyCommonName(boolean value) {
        this.verifyCommonName = value;
      }

      /**
       * <p>Java class for anonymous complex type.
       * 
       * <p>The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="cipherSuite" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
       *       &lt;/sequence>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "cipherSuite" })
      public static class CipherSuites {

        @XmlElement(nillable = true)
        protected List<String> cipherSuite;

        /**
         * Gets the value of the cipherSuite property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cipherSuite property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCipherSuite().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCipherSuite() {
          if (cipherSuite == null) {
            cipherSuite = new ArrayList<String>();
          }
          return this.cipherSuite;
        }

      }

      /**
       * <p>Java class for anonymous complex type.
       * 
       * <p>The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="trustedCertName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
       *       &lt;/sequence>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "trustedCertName" })
      public static class TrustedCertNames {

        protected List<String> trustedCertName;

        /**
         * Gets the value of the trustedCertName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the trustedCertName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTrustedCertName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getTrustedCertName() {
          if (trustedCertName == null) {
            trustedCertName = new ArrayList<String>();
          }
          return this.trustedCertName;
        }

      }

    }

    @Override
    public String toString() {
      return "InboundNodeDef [name=" + name + ", serverAddress=" + serverAddress + ", port=" + port + ", secureConnection=" + secureConnection + "]";
    }

  }

  @Override
  public String toString() {
    return "InboundNodes [nodes=" + (inboundNodeDef == null ? "null" : inboundNodeDef.size()) + "]";
  }

}
