/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("de.denkunddachte.b2biutils.java-application-conventions")
}

dependencies {
    implementation(project(":ddutils"))
    implementation(project(":B2BApiClient"))

    /* Mail API:*/
    implementation("com.sun.mail:jakarta.mail:2.0.1")

    /* Loader */
    implementation("org.apache.poi:poi:5.2.2")
    implementation("org.apache.poi:poi-ooxml:5.2.2")
    implementation("org.apache.logging.log4j:log4j-core:2.18.0")

    /* XML Diff */
    implementation("org.xmlunit:xmlunit-core:2.9.1")
    implementation("org.xmlunit:xmlunit-matchers:2.9.1")

    /* SFTPClient / host key grabber: */
    implementation("com.github.mwiede:jsch:0.2.7")

    /* distribution plugin seems to need this: */
    implementation("org.apache.commons:commons-text")
}

application {
    // Define the main class for the application.
    //mainClass.set("de.dd.app.App")
}
distributions {
    main {
        distributionBaseName.set("B2BiUtils")
        distributionClassifier.set("uhu")
        contents {
            from("scripts/*.sh") {

            }
        }
    }
}
