/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("de.denkunddachte.b2biutils.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":ddutils"))
    implementation(project(":B2BApiClient"))
}

application {
    // Define the main class for the application.
    //mainClass.set("de.dd.app.App")
}
distributions {
    main {
        distributionBaseName.set("B2BiUtils")
        distributionClassifier.set("uhu")
        contents {
            from("scripts/*.sh") {

            }
        }
    }
}
