/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
import org.apache.tools.ant.filters.FixCrLfFilter;

plugins {
    id("de.denkunddachte.b2biutils.java-application-conventions")
    id("de.denkunddachte.b2biutils.java-library-conventions")
}

dependencies {
    implementation(project(":ddutils"))
    implementation(project(":B2BApiClient"))

    /* Loader */
    implementation("org.apache.poi:poi:5.2.2")
    implementation("org.apache.poi:poi-ooxml:5.2.2")
    implementation("org.apache.logging.log4j:log4j-core:2.18.0")
    implementation("org.apache.commons:commons-lang3:3.13.0")

    /* XML Diff */
    implementation("org.xmlunit:xmlunit-core:2.9.1")
    implementation("org.xmlunit:xmlunit-matchers:2.9.1")

    /* SFTPClient / host key grabber: */
    implementation("com.github.mwiede:jsch:0.2.7")

    /* distribution plugin seems to need this: */
    runtimeOnly("org.apache.commons:commons-text")
}

application {
    // Define the main class for the application.
    mainClass.set("de.denkunddachte.b2biutil.workflow.WorkflowUtil")
}

/* Suppress generation of default start scripts by distribution plugin */
tasks.startScripts.configure {
    actions.clear()
}

distributions {
    main {
        distributionBaseName.set("b2butils")
        contents {
            from("$projectDir/scripts") {
                include("*.sh")
                fileMode = "755".toInt(radix = 8)
                filter<FixCrLfFilter>("eol" to FixCrLfFilter.CrLf.newInstance("lf"))
            }
            from("$projectDir/scripts") {
                include("*.cmd")
                fileMode = "644".toInt(radix = 8)
                filter<FixCrLfFilter>("eol" to FixCrLfFilter.CrLf.newInstance("crlf"))
            }
            from("$rootDir") {
                include("LICENSE", "NOTICE", "COPYRIGHT")
                fileMode = "644".toInt(radix = 8)
                filter<FixCrLfFilter>("eol" to FixCrLfFilter.CrLf.newInstance("lf"))
            }
            from("$projectDir") {
                include("apiconfig-sample.properties", "sftp.properties")
                fileMode = "644".toInt(radix = 8)
                filter<FixCrLfFilter>("eol" to FixCrLfFilter.CrLf.newInstance("lf"))
            }
        }
    }
}

/* Install b2biutils locally to ${b2biutils.install.dir} (set in gradle.properties).
*/
tasks.register<Sync>("localInstall") {
    onlyIf {
        !project.properties["b2biutils.install.dir"].toString().isNullOrEmpty()
    }
    dependsOn("installDist")

    from("${project.buildDir}/install/b2butils")
    into(project.properties["b2biutils.install.dir"].toString())
    preserve {
        include("apiconfig.properties")
        include("sshkeys.txt")
    }
}