import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    // Apply the java Plugin to add support for Java.
    java
    checkstyle
    id("com.github.spotbugs")
    id("pl.allegro.tech.build.axion-release") apply true
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.10.0")
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.9.2")
        }
    }
}

project.version  = scmVersion.version
group = "de.denkunddachte"

// Set compatibility to Java 1.8 for now (B2Bi comes with IBMSDK 8)
// Note: newer SSH key types (e.g. EC) are not supported. Use JDK >=11 and set compatibility accordingly:
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks {
    javadoc {
        options.encoding = "UTF-8"
    }
    compileJava {
        options.encoding = "UTF-8"
    }
    compileTestJava {
        options.encoding = "UTF-8"
    }
}

tasks.processResources {
    var buildTime = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").withZone(ZoneOffset.systemDefault()).format(Instant.now())
    expand("version" to project.version,
            "buildTime" to buildTime,
            "implementor" to "Denk&Dachte GmbH",
            "product" to project.name,
            "year" to buildTime.substring(0,4)
    )
}

