/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("de.denkunddachte.b2biutils.java-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

tasks.jar {
    manifest {
        attributes(mapOf("Implementation-Title" to project.name,
            "Implementation-Version" to project.version,
            "Class-Path" to configurations.runtimeClasspath.get().joinToString(" ") { it.name }
        ))
    }
}
